saveExact: true

minimumReleaseAge: 960 # 16 hours in minutes
minimumReleaseAgeExclude:
  - es-toolkit@1.47.0
  - eslint-config-un@1.0.0-beta.12

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days in minutes
trustPolicyExclude:
  # []
  - tinyexec@1.2.2 # Uses staged publishing instead of trusted publishing

allowBuilds:
  # core-js: false # Donation message
  esbuild: false # Not a direct dependency
  lefthook: true
  unrs-resolver: false # cspell:disable-line

dedupePeers: true
strictPeerDependencies: false

overrides:
  '@arethetypeswrong/core@0.18.2>fflate': 0.8.2 # TODO https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/258 cspell:disable-line
  eslint-plugin-jsx-a11y-x@0.1.1: 0.2.0

peerDependencyRules:
  allowedVersions:
    eslint-config-un@1.0.0-beta.11>@e18e/eslint-plugin: '^0.4.1 || ^0.5.0'

patchedDependencies:
  remeda: patches/remeda.patch
