import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {jsonParse} from '../src/json/json-parse.ts';
import {regexEscape} from '../src/regex/regex-escape.ts';
import {ensurePrefix} from '../src/string/ensure-prefix.ts';

const MAIN_BRANCH = 'main';
const SCOPED_PUBLISH_BRANCH = 'feat/scoped-package-publishing';

const ROOT = path.resolve(import.meta.dirname, '..');
const PACKAGE_JSON_PATH = path.join(ROOT, 'package.json');
const README_PATH = path.join(ROOT, 'README.md');
const THIRD_PARTY_NOTICES_PATH = path.join(ROOT, 'THIRD_PARTY_NOTICES.md');

const getCurrentBranch = () => {
  const {GITHUB_REF_NAME: githubRefNameEnv} = process.env;
  if (githubRefNameEnv) {
    return githubRefNameEnv;
  }

  // eslint-disable-next-line sonar/no-os-command-from-path -- `git` is part of the trusted CI/dev toolchain, resolved from a trusted PATH.
  return execFileSync('git', ['rev-parse', '--abbrev-ref', 'HEAD'], {
    cwd: ROOT,
    encoding: 'utf8',
  }).trim();
};

const publish = () => {
  // eslint-disable-next-line sonar/no-os-command-from-path -- `pnpm` is the pinned CI/dev toolchain, resolved from a trusted PATH.
  execFileSync('pnpm', ['exec', 'changeset', 'publish'], {stdio: 'inherit'});
};

// changesets/action finds the published packages by the names from this output, but it reads
// them from `package.json`, which has the unscoped name again by then
const unscopeChangesetsOutput = (scopedName: string, unscopedName: string) => {
  const {CHANGESETS_OUTPUT: changesetsOutputPath} = process.env;
  if (changesetsOutputPath == null || !fs.existsSync(changesetsOutputPath)) {
    return;
  }

  const outputText = fs.readFileSync(changesetsOutputPath, 'utf8');
  fs.writeFileSync(
    changesetsOutputPath,
    outputText.replaceAll(JSON.stringify(scopedName), () => JSON.stringify(unscopedName)),
  );
};

const run = () => {
  const currentBranch = getCurrentBranch();

  if (currentBranch !== MAIN_BRANCH && currentBranch !== SCOPED_PUBLISH_BRANCH) {
    throw new Error(
      `Refusing to publish from "${currentBranch}": releases are only allowed from "${MAIN_BRANCH}" or "${SCOPED_PUBLISH_BRANCH}".`,
    );
  }

  // Files the publish flow mutates in the working tree and must restore afterward. The notices
  // table is (re)generated by `prepublishOnly` on every publish; the scoped name rewrite below
  // only runs on the scoped branch.
  const originalFileContents = new Map<string, string>();
  const snapshot = (filePath: string) => {
    const contents = fs.readFileSync(filePath, 'utf8');
    originalFileContents.set(filePath, contents);
    return contents;
  };

  snapshot(THIRD_PARTY_NOTICES_PATH);

  const isScopedPublish = currentBranch === SCOPED_PUBLISH_BRANCH;
  const packageJsonText = fs.readFileSync(PACKAGE_JSON_PATH, 'utf8');
  const packageJson = jsonParse<{name: string; author: string}>(packageJsonText);
  const {author: packageAuthor, name: packageUnscopedName} = packageJson;
  const scopedName = `${ensurePrefix(packageAuthor, '@')}/${packageUnscopedName}`;

  if (isScopedPublish) {
    originalFileContents.set(PACKAGE_JSON_PATH, packageJsonText);
    packageJson.name = scopedName;
    fs.writeFileSync(PACKAGE_JSON_PATH, `${JSON.stringify(packageJson, null, 2)}\n`);

    const readmeText = snapshot(README_PATH);
    // The lookbehind spares `<author>/<name>` occurrences, i.e. GitHub repository URLs.
    const unscopedNameRegex = new RegExp(
      String.raw`(?<!${regexEscape(packageAuthor)}/)\b${regexEscape(packageUnscopedName)}\b`,
      'g',
    );
    fs.writeFileSync(
      README_PATH,
      readmeText.replaceAll(unscopedNameRegex, () => scopedName),
    );
  }

  try {
    publish();
  } finally {
    for (const [filePath, contents] of originalFileContents) {
      fs.writeFileSync(filePath, contents);
    }

    if (isScopedPublish) {
      unscopeChangesetsOutput(scopedName, packageUnscopedName);
    }
  }
};

run();
